name: tests

on:
  push:
    branches:
      - "*"
    # not on tags
  pull_request:

env:
  BLAKE3_CI: "1"
  RUSTFLAGS: "-D warnings"
  RUST_BACKTRACE: "1"

jobs:
  build_cross_msvc:
    name: build Windows MSVC x86_64 from Linux
    runs-on: ubuntu-latest
    env: 
      XWIN_ARCH: "x86_64"
      XWIN_VARIANT: "desktop"
      XWIN_VERSION: "16"
      CARGO_XWINBUILD_VERSION: "0.2.3"
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
      - name: install dependencies
        run:  sudo apt-get update -y && sudo apt-get install -y clang-tools llvm lld
      - name: symlink clang-cl
        run: sudo ln -s /usr/bin/clang-cl-[1-9][0-9] /usr/bin/clang-cl
      - name: symlink lld-link
        run: sudo ln -s /usr/bin/lld /usr/bin/lld-link
      - name: cache cargo-xwinbuild
        id: cache-cargo-xwinbuild
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-xwinbuild-${{ env.CARGO_XWINBUILD_VERSION }}
      - name: cache xwin
        id: cache-xwin
        uses: actions/cache@v2
        with:
          path: ~/.cache/cargo-xwinbuild
          key: xwin-${{ env.XWIN_ARCH }}-${{ env.XWIN_VARIANT }}-${{ env.XWIN_VERSION }}
      - name: install cargo-xwinbuild
        run: ls ~/.cargo/bin/cargo-xwinbuild || cargo install --version ${{ env.CARGO_XWINBUILD_VERSION }} cargo-xwinbuild
      - name: build blake3
        run: cargo xwinbuild --target x86_64-pc-windows-msvc -vv
      - name: build b3sum
        run: cargo xwinbuild --target x86_64-pc-windows-msvc -vv
        working-directory: ./b3sum
