name: tests

on:
  push:
    branches:
      - "*"
    # not on tags
  pull_request:

env:
  BLAKE3_CI: "1"
  RUSTFLAGS: "-D warnings"
  RUST_BACKTRACE: "1"

jobs:
  build_cross_msvc:
    name: build Windows MSVC x86_64 from Linux
    runs-on: ubuntu-latest
    env: 
      XWIN_ARCH: "x86_64"
      XWIN_VARIANT: "desktop"
      XWIN_VERSION: "16"
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13"
      - name: cache cargo-xwinbuild
        id: cache-cargo-xwinbuild
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-xwinbuild
      - name: cache xwin
        id: cache-xwin
        uses: actions/cache@v2
        with:
          path: ~/.cache/cargo-xwinbuild
          key: xwin-${{ env.XWIN_ARCH }}-${{ env.XWIN_VARIANT }}-${{ env.XWIN_VERSION }}
      - name: install cargo-xwinbuild
        run: cargo install cargo-xwinbuild
      - name: list cache dir before
        run: ls -al ~/.cache/cargo-xwinbuild || true
      - name: build blake3
        run: cargo xwinbuild --target x86_64-pc-windows-msvc
      - name: build b3sum
        run: cargo xwinbuild --target x86_64-pc-windows-msvc
        working-directory: ./b3sum
      - name: list cache dir after
        run: ls -al ~/.cache/cargo-xwinbuild