name: tests

on:
  push:
    branches:
      - "*"
    # not on tags
  pull_request:

env:
  BLAKE3_CI: "1"
  RUSTFLAGS: "-D warnings"
  RUST_BACKTRACE: "1"

jobs:
  test_msvc_linux:
    name: Test Windows MSVC x86_64 on Linux
    runs-on: ubuntu-latest
    env: 
      CARGO_XWINBUILD_VERSION: "0.4.0"
      XWIN_ARCH: "x86_64"
      XWIN_VARIANT: "desktop"
      XWIN_VERSION: "16"
      WINEDEBUG: "-all"
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      # Dependencies
      - name: install dependencies
        run: | 
          sudo apt-get update -y
          sudo apt-get install --quiet -y clang-tools llvm lld 
          sudo ln -s /usr/bin/clang-cl-[1-9][0-9] /usr/bin/clang-cl
          sudo ln -s /usr/bin/lld /usr/bin/lld-link
          sudo apt-get install --quiet --no-install-recommends -y wine-stable winetricks
          winetricks nocrashdialog

      # Cache
      - name: cache cargo-xwinbuild
        id: cache-cargo-xwinbuild
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-xwinbuild-${{ env.CARGO_XWINBUILD_VERSION }}
      - name: cache xwin
        id: cache-xwin
        uses: actions/cache@v2
        with:
          path: ~/.cache/cargo-xwinbuild
          key: xwin-${{ env.XWIN_ARCH }}-${{ env.XWIN_VARIANT }}-${{ env.XWIN_VERSION }}
      - name: install cargo-xwinbuild
        run: ls ~/.cargo/bin/cargo-xwinbuild || cargo install --version ${{ env.CARGO_XWINBUILD_VERSION }} cargo-xwinbuild

      # Print out instruction set support, for debugging.
      - name: print instruction set support
        run: |
          cargo xwinbuild --target x86_64-pc-windows-msvc
          wine ./target/x86_64-pc-windows-msvc/debug/instruction_set_support.exe --quiet
        working-directory: ./tools/instruction_set_support

      # Tests
      - name: test C bindings intrinsics
        run: cargo xwintest --target x86_64-pc-windows-msvc --features=prefer_intrinsics -vv
        working-directory: ./c/blake3_c_rust_bindings